package org.autorepair.data.exceptions

class DataTimeException: Throwable(message = "ERROR, please try again")