package org.autorepair.data.exceptions

class UserExistsException: Throwable(message = "User already exists")